# Generated by Django 2.1.5 on 2019-01-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0004_auto_20190129_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
