# Generated by Django 2.1.5 on 2019-01-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0005_remove_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
